ALTER TABLE companies ADD COLUMN submitted_by_user_id BIGINT REFERENCES users(id);
ALTER TABLE companies ADD COLUMN bank_account_holder VARCHAR(255);
ALTER TABLE companies ADD COLUMN bank_iban VARCHAR(64);
ALTER TABLE companies ADD COLUMN rejection_reason TEXT;

ALTER TABLE companies DROP CONSTRAINT companies_status_check;
ALTER TABLE companies ADD CONSTRAINT companies_status_check
    CHECK (status IN ('ACTIVE','PENDING_VERIFICATION','INACTIVE','SUSPENDED','BLACKLISTED','CLOSED','REJECTED'));

CREATE TABLE company_documents (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    file_url           VARCHAR(500) NOT NULL,
    original_filename  VARCHAR(255) NOT NULL,
    uploaded_at        TIMESTAMP(6) NOT NULL DEFAULT now()
);

CREATE INDEX idx_company_documents_company ON company_documents(company_id);

-- A pending invite to someone who hasn't registered yet has no user row to point at —
-- user_id becomes optional, and invited_email carries the address until registration
-- links it (see CompanyUserServiceImpl.linkPendingInvites).
ALTER TABLE company_users ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE company_users ADD COLUMN invited_email VARCHAR(255);
