CREATE TABLE companies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    legal_name  VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    phone       VARCHAR(255) NOT NULL,
    address     VARCHAR(255) NOT NULL,
    city        VARCHAR(255) NOT NULL,
    country     VARCHAR(255) NOT NULL,
    website     VARCHAR(255) NOT NULL,
    logo_url    VARCHAR(255),
    status      VARCHAR(255) NOT NULL
        CONSTRAINT companies_status_check CHECK (status IN ('ACTIVE','PENDING_VERIFICATION','INACTIVE','SUSPENDED','BLACKLISTED','CLOSED')),
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

CREATE TABLE users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name            VARCHAR(255) NOT NULL,
    last_name             VARCHAR(255) NOT NULL,
    password_hash         VARCHAR(255) NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    phone                 VARCHAR(45)  NOT NULL,
    avatar_url            VARCHAR(500),
    email_verified        BOOLEAN NOT NULL,
    verification_token    VARCHAR(255),
    reset_password_token  VARCHAR(255),
    reset_token_expiry    TIMESTAMP(6),
    enabled               BOOLEAN NOT NULL,
    account_status        VARCHAR(255)
        CHECK (account_status IN ('PENDING','APPROVED','REJECTED','SUSPENDED','ANONYMIZED','BANNED','DEACTIVATED','LOCKED')),
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role    VARCHAR(255)
        CHECK (role IN ('GUEST','COMPANY_CLIENT','RECEPTIONIST','HOTEL_MANAGER','ADMIN','SUPPORT'))
);

CREATE TABLE hotels (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    city         VARCHAR(255) NOT NULL,
    country      VARCHAR(255) NOT NULL,
    address      VARCHAR(255) NOT NULL,
    star_rating  INTEGER NOT NULL,
    status       VARCHAR(255) NOT NULL
        CHECK (status IN ('ACTIVE','INACTIVE','UNDER_RENOVATION','COMINGS_SOON','CLOSED','SUSPENDED')),
    phone        VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    description  TEXT NOT NULL,
    image_url    VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    company_id   BIGINT NOT NULL REFERENCES companies(id)
);

CREATE TABLE rooms (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number           VARCHAR(255) NOT NULL,
    type             VARCHAR(255) NOT NULL
        CHECK (type IN ('SINGLE','DOUBLE','TWIN','TRIPLE','SUITE','JUNIOR_SUITE','DELUXE','PENTHOUSE','FAMILY','CONNECTING','DORMITORY','STUDIO','VILLA','BUNGALOW','ACCESSIBLE')),
    price_per_night  DOUBLE PRECISION NOT NULL,
    capacity         INTEGER NOT NULL,
    floor            INTEGER NOT NULL,
    status           VARCHAR(255) NOT NULL
        CHECK (status IN ('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE','OUT_OF_ORDER')),
    description      TEXT,
    created_at       TIMESTAMP(6) NOT NULL,
    hotel_id         BIGINT NOT NULL REFERENCES hotels(id)
);

CREATE TABLE company_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_role  VARCHAR(255) NOT NULL
        CHECK (company_role IN ('OWNER','MANAGER','RECEPTIONIST','ACCOUNTANT','STAFF')),
    status        VARCHAR(255) NOT NULL
        CHECK (status IN ('ACTIVE','INVITED','PENDING_APPROVAL','INACTIVE','SUSPENDED','REMOVED')),
    invited_at    TIMESTAMP(6) NOT NULL,
    joined_at     TIMESTAMP(6),
    user_id       BIGINT NOT NULL REFERENCES users(id),
    company_id    BIGINT NOT NULL REFERENCES companies(id)
);

CREATE TABLE bookings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in         TIMESTAMP(6) NOT NULL,
    check_out        TIMESTAMP(6) NOT NULL,
    guest_count      INTEGER NOT NULL,
    booking_status   VARCHAR(255) NOT NULL
        CHECK (booking_status IN ('PENDING','CONFIRMED','CHECKED_IN','COMPLETED','CANCELLED','NO_SHOW','PAYMENT_FAILED')),
    total_price      DOUBLE PRECISION NOT NULL,
    special_request  TEXT,
    confirmed_at     TIMESTAMP(6),
    cancelled_at     TIMESTAMP(6),
    created_at       TIMESTAMP(6) NOT NULL,
    user_id          BIGINT NOT NULL REFERENCES users(id),
    room_id          BIGINT NOT NULL REFERENCES rooms(id)
);

CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          DOUBLE PRECISION NOT NULL,
    method          VARCHAR(255) NOT NULL
        CONSTRAINT payments_method_check CHECK (method IN ('CREDIT_CARD','DEBIT_CARD','BANK_TRANSFER','CASH','CRYPTO')),
    currency        VARCHAR(255) NOT NULL,
    transaction_id  VARCHAR(255),
    status          VARCHAR(255) NOT NULL
        CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED','CANCELLED','REFUNDED','PARTIALLY_REFUNDED','CHARGEBACK','EXPIRED')),
    paid_at         TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL,
    booking_id      BIGINT NOT NULL UNIQUE REFERENCES bookings(id)
);

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     TEXT,
    created_at  TIMESTAMP(6) NOT NULL,
    is_approved BOOLEAN NOT NULL,
    booking_id  BIGINT NOT NULL REFERENCES bookings(id),
    user_id     BIGINT NOT NULL REFERENCES users(id),
    room_id     BIGINT NOT NULL REFERENCES rooms(id)
);
