-- Baseline schema (PostgreSQL). Schema ONLY - no data.
--
-- Consolidates the original migrations V1-V18, which mixed schema changes with demo
-- data. The demo catalogue (companies, hotels, rooms, reviews, translations) now lives in
-- db/seed and the local test accounts in db/seed-accounts; both are loaded only where
-- enabled (the "local" profile, or an explicit SPRING_FLYWAY_LOCATIONS for a demo deploy).
-- Integration tests (Testcontainers) and production get exactly this schema.
--
-- Future schema changes: add V2__..., V3__... next to this file. Never edit it in place.

CREATE TABLE bookings (
    id bigint NOT NULL,
    check_in timestamp(6) without time zone NOT NULL,
    check_out timestamp(6) without time zone NOT NULL,
    guest_count integer NOT NULL,
    booking_status character varying(255) NOT NULL,
    total_price double precision NOT NULL,
    special_request text,
    confirmed_at timestamp(6) without time zone,
    cancelled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    room_id bigint NOT NULL,
    CONSTRAINT bookings_booking_status_check CHECK (booking_status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'PAYMENT_FAILED'))
);

ALTER TABLE bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE companies (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    legal_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    website character varying(255) NOT NULL,
    logo_url character varying(255),
    status character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    submitted_by_user_id bigint,
    bank_account_holder character varying(255),
    bank_iban character varying(64),
    rejection_reason text,
    CONSTRAINT companies_status_check CHECK (status IN ('ACTIVE', 'PENDING_VERIFICATION', 'INACTIVE', 'SUSPENDED', 'BLACKLISTED', 'CLOSED', 'REJECTED'))
);

ALTER TABLE companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE company_documents (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    file_url character varying(500) NOT NULL,
    original_filename character varying(255) NOT NULL,
    uploaded_at timestamp(6) without time zone DEFAULT now() NOT NULL
);

ALTER TABLE company_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME company_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE company_users (
    id bigint NOT NULL,
    company_role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    invited_at timestamp(6) without time zone NOT NULL,
    joined_at timestamp(6) without time zone,
    user_id bigint,
    company_id bigint NOT NULL,
    invited_email character varying(255),
    CONSTRAINT company_users_company_role_check CHECK (company_role IN ('OWNER', 'MANAGER', 'RECEPTIONIST', 'ACCOUNTANT', 'STAFF')),
    CONSTRAINT company_users_status_check CHECK (status IN ('ACTIVE', 'INVITED', 'PENDING_APPROVAL', 'INACTIVE', 'SUSPENDED', 'REMOVED'))
);

ALTER TABLE company_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME company_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE hotel_amenities (
    hotel_id bigint NOT NULL,
    amenity character varying(255),
    CONSTRAINT hotel_amenities_amenity_check CHECK (amenity IN ('WIFI', 'BREAKFAST', 'AIR_CONDITIONING', 'PARKING', 'POOL', 'GYM', 'SPA', 'BAR', 'RESTAURANT', 'ROOM_SERVICE', 'AIRPORT_SHUTTLE', 'PET_FRIENDLY', 'ELEVATOR', 'LAUNDRY', 'WORKSPACE', 'TV', 'COFFEE_MAKER', 'HAIR_DRYER', 'LUGGAGE_STORAGE', 'ACCESSIBLE', 'EV_CHARGING', 'NON_SMOKING'))
);

CREATE TABLE hotel_translations (
    id bigint NOT NULL,
    hotel_id bigint NOT NULL,
    locale character varying(5) NOT NULL,
    description text NOT NULL
);

CREATE SEQUENCE hotel_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE hotel_translations_id_seq OWNED BY hotel_translations.id;

CREATE TABLE hotels (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    star_rating integer NOT NULL,
    status character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    description text NOT NULL,
    image_url character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    company_id bigint NOT NULL,
    property_type character varying(255) DEFAULT 'HOTEL'::character varying NOT NULL,
    CONSTRAINT hotels_property_type_check CHECK (property_type IN ('HOTEL', 'APARTMENT')),
    CONSTRAINT hotels_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'UNDER_RENOVATION', 'COMINGS_SOON', 'CLOSED', 'SUSPENDED'))
);

ALTER TABLE hotels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME hotels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE otp_codes (
    id bigint NOT NULL,
    identifier character varying(255) NOT NULL,
    code_hash character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    consumed boolean DEFAULT false NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE otp_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME otp_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE payments (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    method character varying(255) NOT NULL,
    currency character varying(255) NOT NULL,
    transaction_id character varying(255),
    status character varying(255) NOT NULL,
    paid_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    booking_id bigint NOT NULL,
    refund_transaction_id character varying(255),
    refunded_amount double precision DEFAULT 0 NOT NULL,
    CONSTRAINT payments_method_check CHECK (method IN ('CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'CASH', 'CRYPTO', 'GOOGLE_PAY')),
    CONSTRAINT payments_status_check CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'CHARGEBACK', 'EXPIRED'))
);

ALTER TABLE payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE reviews (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text,
    created_at timestamp(6) without time zone NOT NULL,
    is_approved boolean NOT NULL,
    booking_id bigint NOT NULL,
    user_id bigint NOT NULL,
    room_id bigint NOT NULL,
    CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)))
);

ALTER TABLE reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE rooms (
    id bigint NOT NULL,
    number character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    price_per_night double precision NOT NULL,
    capacity integer NOT NULL,
    floor integer NOT NULL,
    status character varying(255) NOT NULL,
    description text,
    created_at timestamp(6) without time zone NOT NULL,
    hotel_id bigint NOT NULL,
    CONSTRAINT rooms_status_check CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', 'OUT_OF_ORDER')),
    CONSTRAINT rooms_type_check CHECK (type IN ('SINGLE', 'DOUBLE', 'TWIN', 'TRIPLE', 'SUITE', 'JUNIOR_SUITE', 'DELUXE', 'PENTHOUSE', 'FAMILY', 'CONNECTING', 'DORMITORY', 'STUDIO', 'VILLA', 'BUNGALOW', 'ACCESSIBLE'))
);

ALTER TABLE rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role character varying(255),
    CONSTRAINT user_roles_role_check CHECK (role IN ('GUEST', 'COMPANY_CLIENT', 'RECEPTIONIST', 'HOTEL_MANAGER', 'ADMIN', 'SUPPORT'))
);

CREATE TABLE users (
    id bigint NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password_hash character varying(255),
    email character varying(255) NOT NULL,
    phone character varying(45),
    avatar_url character varying(500),
    email_verified boolean NOT NULL,
    verification_token character varying(255),
    reset_password_token character varying(255),
    reset_token_expiry timestamp(6) without time zone,
    enabled boolean NOT NULL,
    account_status character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    google_id character varying(255),
    date_of_birth date,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp(6) without time zone,
    token_valid_after timestamp(6) without time zone,
    CONSTRAINT users_account_status_check CHECK (account_status IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'ANONYMIZED', 'BANNED', 'DEACTIVATED', 'LOCKED'))
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY hotel_translations ALTER COLUMN id SET DEFAULT nextval('hotel_translations_id_seq'::regclass);

ALTER TABLE ONLY bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY company_documents
    ADD CONSTRAINT company_documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY company_users
    ADD CONSTRAINT company_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hotel_translations
    ADD CONSTRAINT hotel_translations_hotel_id_locale_key UNIQUE (hotel_id, locale);

ALTER TABLE ONLY hotel_translations
    ADD CONSTRAINT hotel_translations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY hotels
    ADD CONSTRAINT hotels_pkey PRIMARY KEY (id);

ALTER TABLE ONLY otp_codes
    ADD CONSTRAINT otp_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY payments
    ADD CONSTRAINT payments_booking_id_key UNIQUE (booking_id);

ALTER TABLE ONLY payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);

ALTER TABLE ONLY rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT uq_users_email UNIQUE (email);

ALTER TABLE ONLY users
    ADD CONSTRAINT uq_users_google_id UNIQUE (google_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_company_documents_company ON company_documents USING btree (company_id);

CREATE INDEX idx_hotel_translations_hotel_locale ON hotel_translations USING btree (hotel_id, locale);

CREATE INDEX idx_otp_codes_identifier ON otp_codes USING btree (identifier);

ALTER TABLE ONLY bookings
    ADD CONSTRAINT bookings_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id);

ALTER TABLE ONLY bookings
    ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY companies
    ADD CONSTRAINT companies_submitted_by_user_id_fkey FOREIGN KEY (submitted_by_user_id) REFERENCES users(id);

ALTER TABLE ONLY company_documents
    ADD CONSTRAINT company_documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;

ALTER TABLE ONLY company_users
    ADD CONSTRAINT company_users_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);

ALTER TABLE ONLY company_users
    ADD CONSTRAINT company_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY hotel_amenities
    ADD CONSTRAINT hotel_amenities_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotels(id);

ALTER TABLE ONLY hotel_translations
    ADD CONSTRAINT hotel_translations_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE;

ALTER TABLE ONLY hotels
    ADD CONSTRAINT hotels_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);

ALTER TABLE ONLY payments
    ADD CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id);

ALTER TABLE ONLY reviews
    ADD CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id);

ALTER TABLE ONLY reviews
    ADD CONSTRAINT reviews_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id);

ALTER TABLE ONLY reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY rooms
    ADD CONSTRAINT rooms_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotels(id);

ALTER TABLE ONLY user_roles
    ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
