-- Passwordless auth: an account can now exist via email+code with no password ever set
-- (and, once Google is linked, no password at all), so password_hash can no longer be
-- mandatory. Phone was always collected at registration before; the new flow doesn't
-- ask for it, so it must become optional too.
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE users ALTER COLUMN phone DROP NOT NULL;

ALTER TABLE users ADD COLUMN google_id VARCHAR(255);
ALTER TABLE users ADD CONSTRAINT uq_users_google_id UNIQUE (google_id);

-- Collected at signup in the new account-creation step; nullable because Google-linked
-- accounts and the 7 existing pre-migration users never provided one.
ALTER TABLE users ADD COLUMN date_of_birth DATE;

-- Email was only uniqued at the application layer before; the new flow depends on it
-- being the account key for the code-based login/register branch, so enforce it in the DB.
ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email);

CREATE TABLE otp_codes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier  VARCHAR(255) NOT NULL,
    code_hash   VARCHAR(255) NOT NULL,
    expires_at  TIMESTAMP(6) NOT NULL,
    attempts    INTEGER NOT NULL DEFAULT 0,
    consumed    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_otp_codes_identifier ON otp_codes (identifier);
